name: mhd_virtual_table
description: App with list of virtual tables for MHD in Bratislava.
version: 0.9.0
authors: 
- magicsk.eu <support@magicsk.eu>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.15.1
  flutter_webview_plugin: ^0.3.5
  webview_flutter: ^0.3.9+1
  permission_handler: '^3.1.0'
  http: ^0.12.0+2
  diacritic: ^0.1.1
  draggable_scrollbar: ^0.0.4
  geolocator: ^5.0.0
  path_provider: ^1.1.2
  easy_alert: ^0.0.2
  connectivity: ^0.4.2
  persist_theme: ^1.5.1
  shared_preferences: ^0.5.3+2
  provider: ^3.0.0+1
  scoped_model: ^1.0.1
  preferences: ^4.0.0
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  cupertino_icons: ^0.1.2
  flutter_cupertino_localizations: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.5


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
