name: mhd_virtual_table
description: App with list of virtual tables for MHD in Bratislava.
version: 1.4.1
authors:
  - magicsk.eu <support@magicsk.eu>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # intl: ^0.16.0
  flutter_webview_plugin: ^0.3.11
  webview_flutter: ^1.0.7
  permission_handler: ^5.0.1+1
  http: ^0.12.2
  diacritic: ^0.1.1
  draggable_scrollbar: ^0.0.4
  geolocator: ^6.1.13
  path_provider: ^1.6.24
  easy_alert: ^0.0.8
  connectivity: ^2.0.2
  persist_theme: ^1.7.0
  shared_preferences: ^0.5.12+4
  localstorage: ^3.0.6+9
  provider: ^4.3.2+3
  preferences: ^5.2.1
  flutter_typeahead: ^1.9.1
  loading_overlay: ^0.2.1
  native_color: ^1.2.0+1
  animated_list_view: ^0.1.1
  flutter_dotenv: ^2.1.0
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  # intl_translation: ^0.17.5

# The following section is specific to Flutter.
flutter:
  assets:
    - .env
    - assets/google/powered_by_google_on_non_white.png
    - assets/google/2.0x/powered_by_google_on_non_white.png
    - assets/google/3.0x/powered_by_google_on_non_white.png
    - assets/google/powered_by_google_on_white.png
    - assets/google/2.0x/powered_by_google_on_white.png
    - assets/google/3.0x/powered_by_google_on_white.png
  uses-material-design: true